/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
   
    public static void main(String[] args) {
     // Crear personas
        Persona persona1 = new Persona("Juan Pérez", 34222111);
        Persona persona2 = new Persona("María García", 28999000);
        Persona persona3 = new Persona("Carlos Rodríguez", 41555222);
        Persona persona4 = new Persona("Ana Martínez", 39888777);

        // Crear profesores
        Profesor profesor1 = new Profesor("LP001", persona1);
        Profesor profesor2 = new Profesor("LP002", persona2);

        // Crear alumnos
        Alumno alumno1 = new Alumno(persona3);
        Alumno alumno2 = new Alumno(persona4);

        // Crear asistentes
        Asistente asistente1 = new Asistente(persona4); // Ana Martínez será asistente

        // Crear un curso con un profesor y un asistente
        RegistroParticipantes registro1 = new RegistroParticipantes("Programacion I", "Martes 18-21hs");
        Curso curso1 = new Curso("Programacion I", "Martes 18-21hs", 30, registro1);
        curso1.setProfesorACargo(profesor1); // Juan Pérez dictará el curso
        curso1.setAsistenteACargo(asistente1); // Ana Martínez será la asistente

        // Inscribir alumnos en el curso
        curso1.inscribirAlumno(alumno1); // Carlos Rodríguez se inscribe
        curso1.inscribirAlumno(alumno2); // Ana Martínez se inscribe como alumna (¡puede ser asistente y alumna!)


       //mostrar los datos del curso
        curso1.imprimirResumen();

        // Crear otro curso con otro profesor
        RegistroParticipantes registro2 = new RegistroParticipantes("Matemática II", "Jueves 10-13hs");
        Curso curso2 = new Curso("Matemática II", "Jueves 10-13hs", 20, registro2);
        curso2.setProfesorACargo(profesor2); // María García dictará el curso

        //Un profesor puede ser alumno de otro curso
        curso2.inscribirAlumno(profesor1); // Juan Pérez se inscribe en Matemática II


        // Mostrar los datos del curso
        curso2.imprimirResumen();
    }
}
