/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.example.gui;

// --- AGREGA ESTAS LÍNEAS ---
import org.example.Alumno;
import javax.swing.JOptionPane;
import org.example.SistemaGestion;

/**
 *
 * @author Evelyn
 */
public class DialogGestionAlumnos extends javax.swing.JDialog {
private final SistemaGestion sistema; 
    /**
     * Creates new form DialogGestionAlumnos
     */
    public DialogGestionAlumnos(java.awt.Frame parent, boolean modal, SistemaGestion sistema) {
        super(parent, modal);
    this.sistema = sistema;
    initComponents();
    cargarAlumnosEnTabla();
    pack();
    }
    
    private void cargarAlumnosEnTabla() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaAlumnos.getModel();
    
    model.setRowCount(0);
    
    java.util.List<org.example.Alumno> alumnos = sistema.getAlumnos();
    
    for (org.example.Alumno alumno : alumnos) {
        model.addRow(new Object[]{
            alumno.getNumeroDocumento(),
            alumno.getNombre(),
            alumno.getApellido()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorTabla = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "NOMBRE", "APELLIDO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        contenedorTabla.setViewportView(tablaAlumnos);

        btnAgregar.setText("Agregar Alumno");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    String dni = JOptionPane.showInputDialog(this, "Ingrese el DNI del alumno:", "Nuevo Alumno", JOptionPane.QUESTION_MESSAGE);
    
    if (dni != null && !dni.trim().isEmpty()) {
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del alumno:", "Nuevo Alumno", JOptionPane.QUESTION_MESSAGE);
        String apellido = JOptionPane.showInputDialog(this, "Ingrese el apellido del alumno:", "Nuevo Alumno", JOptionPane.QUESTION_MESSAGE);

        if (nombre != null && apellido != null) {
            Alumno nuevoAlumno = new Alumno(dni, nombre, apellido);
            
            this.sistema.agregarAlumno(nuevoAlumno);
            
            cargarAlumnosEnTabla();
            
            JOptionPane.showMessageDialog(this, "Alumno agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JScrollPane contenedorTabla;
    private javax.swing.JTable tablaAlumnos;
    // End of variables declaration//GEN-END:variables
}
